apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-env"
  labels:
    {{- include "chia-blockchain.labels" . | nindent 4 }}
data:
  CHIA_ROOT: {{ .Values.chia.chia_root }}
  self_hostname: {{ .Values.chia.hostname }}
  keys: {{ .Values.chia.keys }}
  service: {{ .Values.chia.service }}
  log_level: {{ .Values.chia.log_level }}
  ca: {{ and (gt (len .Values.chia.ca.private_ca_crt) 0) (gt (len .Values.chia.ca.private_ca_key) 0) | ternary "/chia-ca" ""  | quote }}
  testnet: "{{ .Values.chia.testnet }}"
  {{- toYaml .Values.chia.env | nindent 2 }}
