apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-env"
  labels:
    {{- include "chia-blockchain.labels" . | nindent 4 }}
data:
  self_hostname: {{ .Values.chia.hostname }}
  keys: {{ .Values.chia.keys }}
  service: {{ .Values.chia.service }}
