apiVersion: apps/v1
kind: {{ .Values.installationType }}
metadata:
  name: {{ include "chia-blockchain.fullname" . }}
  labels:
    {{- include "chia-blockchain.labels" . | nindent 4 }}
spec:
  {{- if eq .Values.installationType "Deployment" }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chia-blockchain.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chia-blockchain.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chia-blockchain.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: daemon
              containerPort: {{ .Values.chia.daemonPort }}
              protocol: TCP
            - name: peers
              containerPort: {{ .Values.chia.fullNodePort }}
              protocol: TCP
            - name: rpc
              containerPort: {{ .Values.chia.fullNodeRPCPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: "{{ $.Release.Name }}-env"
          volumeMounts:
            - name: secret-ca
              mountPath: /chia-ca
          livenessProbe:
            exec:
              command:
                - bash
                - /usr/local/bin/docker-healthcheck.sh
          readinessProbe:
            exec:
              command:
                - bash
                - /usr/local/bin/docker-healthcheck.sh
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: secret-ca
          secret:
            secretName: "{{ .Release.Name }}-ca"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
