{{- if or .Values.chiaExporter.maxmind.enabled .Values.chiaExporter.mysql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-exporter"
  labels:
    {{- include "chia-blockchain.labels" . | nindent 4 }}
stringData:
{{- if .Values.chiaExporter.maxmind.enabled }}
  CHIA_EXPORTER_MAXMIND_COUNTRY_DB_PATH: ""
  CHIA_EXPORTER_MAXMIND_ASN_DB_PATH: ""
{{- end }}
{{- if .Values.chiaExporter.mysql.enabled }}
  CHIA_EXPORTER_MYSQL_HOST: ""
  CHIA_EXPORTER_MYSQL_PORT: ""
  CHIA_EXPORTER_MYSQL_USER: ""
  CHIA_EXPORTER_MYSQL_PASSWORD: ""
  CHIA_EXPORTER_MYSQL_DB_NAME: ""
  CHIA_EXPORTER_MYSQL_BATCH_SIZE: ""
{{- end }}
{{- end }}
