apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-exporter"
  labels:
    {{- include "chia-blockchain.labels" . | nindent 4 }}
stringData:
{{- if .Values.chiaExporter.maxmind.enabled }}
  CHIA_EXPORTER_MAXMIND_COUNTRY_DB_PATH: "{{ .Values.chiaExporter.maxmind.country_db_path }}"
  CHIA_EXPORTER_MAXMIND_ASN_DB_PATH: "{{ .Values.chiaExporter.maxmind.asn_db_path }}"
{{- end }}
{{- if .Values.chiaExporter.mysql.enabled }}
  CHIA_EXPORTER_MYSQL_HOST: "{{ .Values.chiaExporter.mysql.host }}"
  CHIA_EXPORTER_MYSQL_PORT: "{{ .Values.chiaExporter.mysql.port }}"
  CHIA_EXPORTER_MYSQL_USER: "{{ .Values.chiaExporter.mysql.user }}"
  CHIA_EXPORTER_MYSQL_PASSWORD: "{{ .Values.chiaExporter.mysql.password }}"
  CHIA_EXPORTER_MYSQL_DB_NAME: "{{ .Values.chiaExporter.mysql.db_name }}"
  CHIA_EXPORTER_MYSQL_BATCH_SIZE: "{{ .Values.chiaExporter.mysql.batch_size }}"
{{- end }}
