apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-ca"
  labels:
    {{- include "chia-blockchain.labels" . | nindent 4 }}
data:
  private_ca.crt: "{{ .Values.chia.ca.private_ca_crt | b64enc }}"
  private_ca.key: "{{ .Values.chia.ca.private_ca_key | b64enc }}"
  chia_ca.crt: "{{ .Values.chia.ca.chia_ca_crt | b64enc }}"
  chia_ca.key: "{{ .Values.chia.ca.chia_ca_key | b64enc }}"
