{{- if .Values.chiaExporter.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chia-blockchain.fullname" . }}-metrics
  labels:
    {{- include "chia-blockchain.labels" . | nindent 4 }}
    {{- with .Values.chiaExporter.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.metricsService.type }}
  ports:
    - port: 9914
      targetPort: metrics
      protocol: TCP
      name: {{ .Values.chiaExporter.service.portName }}
  selector:
    {{- include "chia-blockchain.selectorLabels" . | nindent 4 }}
{{- end }}
