apiVersion: v1
kind: Service
metadata:
  name: {{ include "chia-blockchain.fullname" . }}
  labels:
    {{- include "chia-blockchain.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.ports.daemon }}
      targetPort: daemon
      protocol: TCP
      name: daemon
    - port: {{ .Values.ports.peers }}
      targetPort: peers
      protocol: TCP
      name: peers
    - port: {{ .Values.ports.rpc }}
      targetPort: rpc
      protocol: TCP
      name: rpc
  selector:
    {{- include "chia-blockchain.selectorLabels" . | nindent 4 }}
