{{- if .Values.mysql.enabled -}}
apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: {{ include "generic.shortname" . }}-mysql
spec:
  secretName: {{ include "generic.fullname" . }}-mysql-root
  tlsUseSelfSigned: true
  instances: {{ .Values.mysql.instances }}
  router:
    instances: {{ .Values.mysql.routerInstances }}
{{- end }}
