{{- if .Values.deployment.secretEnvironment }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-main-env"
  labels:
    {{- include "generic.labels" . | nindent 4 }}
stringData:
  {{- toYaml .Values.deployment.secretEnvironment | trim | nindent 2 }}
{{- end }}
