{{- if .Values.mysql.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic.shortname" . }}-mysql-root
stringData:
  rootHost: "%"
  rootUser: "{{ .Values.mysql.rootUser.user }}"
  rootPassword: "{{ .Values.mysql.rootUser.password }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic.shortname" . }}-mysql-user
stringData:
  DB_USER: "{{ .Values.mysql.standardUser.user }}"
  DB_PASSWORD: "{{ .Values.mysql.standardUser.password }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic.shortname" . }}-mysql-read
stringData:
  DB_READ_ONLY_USER: "{{ .Values.mysql.readOnlyUser.user }}"
  DB_READ_ONLY_PASSWORD: "{{ .Values.mysql.readOnlyUser.password }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic.shortname" . }}-mysql-info
stringData:
  DB_HOST: {{ include "generic.shortname" . }}-mysql
  DB_NAME: "{{ .Values.mysql.dbName }}"
{{- end }}
