apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-files"
  labels:
    {{- include "generic.labels" . | nindent 4 }}
stringData:
  {{- range $.Values.secretFiles }}
  {{ .filename }}: |
    {{- .content | nindent 4 }}
  {{- end }}
