{{- if .Values.mysql.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.name }}-mysql-root"
stringData:
  rootHost: "%"
  rootUser: "{{ .Values.mysql.rootUser.user }}"
  rootPassword: "{{ .Values.mysql.rootUser.password }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.name }}-mysql-user"
stringData:
  DB_HOST: "{{ .Values.name }}-mysql"
  DB_USER: "{{ .Values.mysql.standardUser.user }}"
  DB_PASSWORD: "{{ .Values.mysql.standardUser.password }}"
  DB_NAME: "{{ .Values.mysql.name }}"
{{- end }}
