{{- range .Values.sidecars }}
{{- if .secretEnvironment }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $.Release.Name }}-{{ .name }}-env"
  labels:
    {{- include "generic.labels" $ | nindent 4 }}
stringData:
  {{- toYaml .secretEnvironment | trim | nindent 2 }}
{{- end }}
{{- end }}
