apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-env"
  labels:
    {{- include "generic.labels" . | nindent 4 }}
stringData:
  {{- toYaml .Values.secretEnvironment | trim | nindent 2 }}
