{{- if and .Values.serviceAccount.create (gt (len .Values.serviceAccount.clusterRoleRules) 0) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "generic.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "generic.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "generic.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
