apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-env"
  labels:
    {{- include "generic-stateful.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configmapEnvironment | trim | nindent 2 }}
